### ISSUE TITLE
Add .NET publication target for JSII construct

### ISSUE THREAD

**Issue by scrthq** [mbonig/secret#1]
Hey Matt! Adding the issue here to track .NET readiness for this custom construct. I'd love to test it out once ready! Looking for opportunities to test with either TS or Python in the meantime. 

Thank you for creating this construct!

**Comment by mbonig** [comment]
Thanks for opening this. It's published now and should be available here shortly:

https://www.nuget.org/packages/MBonig.Secret/

**Comment by scrthq** [comment]
Thank you so much for the Construct and the quick turnaround, @mbonig ! I'll test this as soon as possible!

**Comment by scrthq** [comment]
Thank you so much for the Construct and the quick turnaround, @mbonig ! I'll test this as soon as possible!
